# Netlify Configuration for reMarkable Document Optimizer
# Based on Netlify best practices (2025)

[build]
  # No build command needed for static site
  publish = "."
  
[build.environment]
  # Static site - no build environment needed

# Redirect rules for SPA-like behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  
# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # HTTP Strict Transport Security
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    # Content Security Policy
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self' data:; connect-src 'self' blob:; worker-src 'self' blob:;"
    # Prevent clickjacking
    X-Frame-Options = "SAMEORIGIN"
    # Prevent MIME type sniffing
    X-Content-Type-Options = "nosniff"
    # Referrer policy
    Referrer-Policy = "strict-origin-when-cross-origin"
    # XSS Protection
    X-XSS-Protection = "1; mode=block"
    # Permissions Policy
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Cache static assets
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
